const data = [
    {name: 'WaxSnax Cheeseburger',
    image: '../Products/burger.jpg',
    rating: 3,
    reviews: [{title: 'title', content: 'Wax!', rating: 3},
                {title: 'woop', content: 'rah', rating: 2}]},
    {name: 'Cherry Pie',
    image: '../Products/cherryPie.jpg',
    rating: 4,
    reviews: [{title: 'title', content: 'Wax!', rating: 3},
                {title: 'wooh', content: 'rap', rating: 1}]},
    {name: 'Finger Food',
    image: '../Products/fingerFood.jpg',
    rating: 3,
    reviews: [{title: 'title', content: 'Wax!', rating: 3},
                {title: 'woop', content: 'rah', rating: 2}]},
    {name: 'Fruit Basket',
    image: '../Products/fruitBasket.jpg',
    rating: 3,
    reviews: [{title: 'title', content: 'Wax!', rating: 3},
                {title: 'woop', content: 'rah', rating: 2}]},
    {name: 'Ice Cream',
    image: '../Products/iceCream.jpg',
    rating: 3,
    reviews: [{title: 'title', content: 'Wax!', rating: 3},
                {title: 'woop', content: 'rah', rating: 2}]},
    {name: 'Meatball Sub',
    image: '../Products/meatbullSub.jpg',
    rating: 3,
    reviews: [{title: 'title', content: 'Wax!', rating: 3},
                {title: 'woop', content: 'rah', rating: 2}]},
    {name: 'Pho',
    image: '../Products/pho.jpg',
    rating: 3,
    reviews: [{title: 'title', content: 'Wax!', rating: 3},
                {title: 'woop', content: 'rah', rating: 2}]},
    {name: 'Pizza',
    image: '../Products/pizza.jpg',
    rating: 3,
    reviews: [{title: 'title', content: 'Wax!', rating: 3},
                {title: 'woop', content: 'rah', rating: 2}]},
    {name: 'Shrimp Cocktail',
    image: '../Products/shrimpCocktail.jpg',
    rating: 3,
    reviews: [{title: 'title', content: 'Wax!', rating: 3},
                {title: 'woop', content: 'rah', rating: 2}]},
    {name: 'Stir Fry',
    image: '../Products/stirfry.jpg',
    rating: 3,
    reviews: [{title: 'title', content: 'Wax!', rating: 3},
                {title: 'woop', content: 'rah', rating: 2}]},
    {name: 'Turkey Platter',
    image: '../Products/turkeyPlatter.jpg',
    rating: 3,
    reviews: [{title: 'title', content: 'Wax!', rating: 3},
                {title: 'woop', content: 'rah', rating: 2}]},
    {name: 'Veggie Platter',
    image: '../Products/veggiePlatter.jpg',
    rating: 3,
    reviews: [{title: 'title', content: 'Wax!', rating: 3},
                {title: 'woop', content: 'rah', rating: 2}]}]